### ISSUE TITLE
Take the requirements feature from beta to a full feature

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1865]
Issue  #379 asked for a requirements feature. That is now in beta after PR #1857 

SEE top level issue #2241 that is now the parent of this. 

This issue has some little leftover details that need resolving though:

To do: (some of these may be done, but please check and if they are done, click the box to indicate so)

- [x] Create error messages in en.error and raise them properly - there are System.out.println("ERROR") messages instead of the error codes in the cruise.umple/src/class/UmpleInternalParser_CodeClass.ump : 221, 238 analyzeImplementReq() function. This is subissue #2052 
- [x] Add syntax highlighting of the req and implementsdReq keywords (but wait until the Codemirror6 pull request is merged)
- [ ] Add requirements to "User Manual Basics: List of Umple Keywords" and "Grammar to Define Umple" sections in user manual
- [ ] Add style to the generated requirements document (cruise.umple/src/generators/Generator_CodePlainRequirementsDoc.ump)
- [ ] Sort requirements in alphabetical order. Further instructions on line 57 of Generator_CodePlainRequirementsDoc.ump
- [ ] Add tests to the requirements doc generator (this should be done with all subissues including #2051, #2052, #2053 etc.)
- [ ] Modify Mixsets to contain a HashMap of requirements (just like the Umple Model) and alter methods analyzeRequirement() line 203 and analyzeImplementReq() line 221, 238 in UmpleInternalParser_CodeClass.ump to add or take requirements from the appropriate spot (e.g. if stored in mixset, get from mixset and otherwise from the model). This may be relevant to #2051
- [ ] Modify function translateToHTML() at cruise.umple/src/Umple_Code.ump : 889 to account for requirement language styles (like markdown) in the generated requirements doc
- [ ] For requirements to appear as a tooltip in the GV Class Diagram, modify or create a similar function to appendTooltipComment() found in cruise.umple/src/generators/Generator_SuperGvGenerator.ump : 137
- [x] Add a generate plain requirements doc option to UmpleOnline. This should be done when the requirements feature is working well (i.e. closer to being out of beta)

**Comment by TimLethbridge** [comment]
The above is the  core of the project, however the ideal outcome would be to be able do do much more like to be able to show the requirements for various mixsets, or to represent requirements in different requirements languages

**Comment by TimLethbridge** [comment]
If this project is done well, we can write a paper about managing requirements in the same codebase as the code, with mixsets, mixins, and so on.

**Comment by TimLethbridge** [comment]
See also issue #2297 as this would require extending what is parsable in Umple
